title: Página Chulísima
logo: https://web.dev/static/articles/building/an-adaptive-favicon/image/example-dark-theme-favico-6a6f6f67bc3e7.png
favicon: https://web.dev/static/articles/building/an-adaptive-favicon/image/example-dark-theme-favico-6a6f6f67bc3e7.png
description: olakase
theme: just-the-docs

url: https://just-the-docs.github.io

search_enabled: false
color_scheme: dark
